### ISSUE TITLE
Fails on a Vagrant Centos 7.4

### ISSUE THREAD

**Issue by mhightower** [geerlingguy/ansible-role-repo-remi#13]
First time using the role but it is failing on a Centos 7.4  vagrant box. I think it is a key issue.

`TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
fatal: [ansible.dev]: FAILED! => {"changed": false, "msg": "warning: /tmp/remi-release-7Of2mls.rpm: Header V4 DSA/SHA1 Signature, key ID 00f97f56: NOKEY\n\n\nPublic key for remi-release-7Of2mls.rpm is not installed\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nExamining /tmp/remi-release-7Of2mls.rpm: remi-release-7.4-2.el7.remi.noarch\nMarking /tmp/remi-release-7Of2mls.rpm to be installed\nResolving Dependencies\n--> Running transaction check\n---> Package remi-release.noarch 0:7.4-2.el7.remi will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch       Version            Repository                 Size\n================================================================================\nInstalling:\n remi-release     noarch     7.4-2.el7.remi     /remi-release-7Of2mls      15 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal size: 15 k\nInstalled size: 15 k\nDownloading packages:\n"]}`

From a brief search I couldn't tell if 7.4 was supported or not.

**Comment by mhightower** [comment]
I actually wanted to run this role on a Centos7.3 box and it worked just fine.

**Comment by mhightower** [comment]
Had to run

     pre_tasks:
        - name: Import remi GPG key. (Fails during PHP install)
          rpm_key:
               key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
               state: present

to get it to work.

**Comment by ericsysmin** [comment]
@mhightower is this still an issue? It seems resolved as I have tried on 7.4 without issue and the key is listed here 
https://github.com/geerlingguy/ansible-role-repo-remi/blob/master/tasks/main.yml

**Comment by geerlingguy** [comment]
I'll go ahead and close this for now as I can't reproduce the issue either on VirtualBox or in Docker. If you can find a reproducible test case, please post a playbook or tasks that cause this to happen.

**Comment by victorbiga** [comment]
I had the same error, found that RPM release 7 was not pulling it. The playbook below worked fine for me
```
---
- hosts: all
  become: yes

  tasks:

  - name: Install remi repo.
    yum:
      name: "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
      state: present
```
