### ISSUE TITLE
geerlingguy.repo-remi not working on rhel8

### ISSUE THREAD

**Issue by MacFlurry** [geerlingguy/ansible-role-repo-remi#22]
Hello sir :-) 

geerlingguy.repo-remi is not working on rhel8

```
TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
fatal: [rhel8]: FAILED! => changed=false
  failures: []
  msg: |-
    Depsolve Error occured:
     Problem: conflicting requests
      - nothing provides epel-release = 8 needed by remi-release-8.1-2.el8.remi.noarch
  rc: 1
  results: []
```

tested with:
```
  - name: rhel8
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubi8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```
